pretrained_models=(
    "bert-base-multilingual-cased"
    "setu4993/LaBSE"
    "xlm-roberta-base"
    "google/mt5-base"
    "cis-lmu/glot500-base"
    "facebook/nllb-200-distilled-600M"
    "ai4bharat/indic-bert"
    "Davlan/afro-xlmr-large"
    )